### ISSUE TITLE
How to set up

### ISSUE THREAD

**Issue by CatnHat** [welshfox/MultiBot-Utility#1]
Not exactly sure how to set this up, i ran the batch file.

**Comment by welshfox** [comment]
do you have python 2.7 installed?

**Comment by welshfox** [comment]
You will need to install Python 2.7, the launch.bat file only works if you have 'python' recognized as a command. If you do not, then use the file path to python.exe (I.E.: "C:\Python27\python.exe"). 

Before running the tool you will need to setup your multi tool config file. This file is where you can setup all of the accounts that you want to run simultaneously. Use the examples provided to get an understanding of what you need to do. It is important to note that each account should be numbered uniquely. An easy way to achieve this is by sequentially numbering them. (I.E. 'Account_0', 'Account_1', Account_2, etc.) When setting up your bots do this in a similar fashion and number them sequentially. The bot sections require you provide the name of the config files within the bot's folder. If the bot uses one config file for both, username and location, then type in the filename.extension into both fields. You will also need to provide the filename.extension of the bot's launcher. Finally, you need to enter in the name of the folder you will be putting the bot into. It is smart to keep your bots within the provided 'Bots' folder. Note: The name field is what you will see when selecting which bot to run your accounts with on after starting the utility,

The last step is to replace all of the fields in the actual bot config with the provided text you will see in the config notes. (I.E. 'MULTIBOTACCOUNTTYPE', 'MULTIBOTLATITUDE', 'MULTIBOTACCOUNTTYPE', etc.) It is important to only place quotes around the text is that is what the actual bot uses around its config fields. If you are using a config that does not use quotes then do not put quotes around this text.

Once you correctly have all of the configs set and the bot folder within the 'Bots' folder provided. You can launch the .bat file. On start it will list the bots you added to the config file. You will type the corresponding number and press 'Enter'. The bot will then cycle through all of your accounts provided and configure the bots config to match. It will start the bot for each account in this manner.

If you set the config to enable restarts then it will close each bot after the amount of minutes you chose. The timer begins after the last bot has started. It will then repeat the process by launching them all up again with the original chosen bot and then restart the timer once completed.

**Comment by CatnHat** [comment]
Thanks again :) i definitely will try this when they get the bots working again, in the meantime ill just analyze your code

**Comment by welshfox** [comment]
What .exe are you talking about? If you are talking about a config file that contains the text '.exe' in the file name then it is best not to make any copies manually. Instead just setup the config file as instructed and let the utility make a template duplicate for you. Once it has generated its template file you can then use that to make any changes to the settings as needed. If this does not make sense then could you please describe a little more about what you asking. Thanks.
